### ISSUE TITLE
User can set a minimum moisture, maximum moisture, and choose whether to auto_water their garden

### ISSUE THREAD

**Issue by bplantico** [Mycobee/garden_pi_fe#31]
As a user,
when I navigate to a page with my garden's settings,
then I can:
- [ ] Set a minimum moisture level
- [ ] Set a maximum moisture level
- [ ] Choose (true/false) whether to use automatic watering (radio button?)

+ Max moisture level is not required
+ Min moisture level is not required unless auto_water is set to TRUE
+ columns in db (i.e. params to send to back end):
`min_moisture` float
`max_moisure` float
`auto_water` boolean

**Comment by David5280** [comment]
Group decided against this for now, good idea for future iterations.
